### ISSUE TITLE
MAoT Highest point near location Errors 999999, 010213, 010325, 010067 and warning error 000950

### ISSUE THREAD

**Issue by erikreid** [Esri/solutions-geoprocessing-toolbox#120] opened 2014-09-17 23:11 UTC
Ran the tool and received Errors 999999, 010213, 010325, 010067 and warning error 000950. Could be due to version difference of the tool and current builds/services.

Error 010213: Error in reading grid <value> " There was an error encountered when trying to read the specified grid. Problems accessing a grid are most commonly the result of missing required component files in the grid's folder. Consult the documentation to see the required files for the ESRI Grid format. If all of the required components are present, it is also possible that the files that contain the binary raster data are internally corrupted."

Error 010325: Run-time error - *** "The tool or method encountered an error during execution. This is a general response that may be used for many possible error conditions or where a specific cause could not be trapped."

Error 010067: Error in executing grid expression "There was a problem executing the map algebra expression"

![find local peaks error message](https://cloud.githubusercontent.com/assets/8561343/4312862/d1db6518-3ebf-11e4-978f-19b8385956b8.png)

**Comment by mfunk** [comment] 2015-02-23 17:20
Tried this again today with elevation service from AFMIEDEV (NSEC elevation service is not available)..
...
Unfortunately i'm still getting errors when running this from services...
```
Executing: HighestPointsNearLocations2 imp "5 Kilometers" "World Elevation Service" C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0001
Start Time: Mon Feb 23 09:14:44 2015
Executing (Buffer): Buffer imp "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\locBuffer" "5 Kilometers" FULL ROUND NONE # PLANAR
Start Time: Mon Feb 23 09:14:44 2015
Succeeded at Mon Feb 23 09:14:45 2015 (Elapsed Time: 0.64 seconds)
Executing (Minimum Bounding Geometry): MinimumBoundingGeometry "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\locBuffer" "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\bufferMBG" RECTANGLE_BY_AREA NONE # NO_MBG_FIELDS
Start Time: Mon Feb 23 09:14:45 2015
Succeeded at Mon Feb 23 09:14:45 2015 (Elapsed Time: 0.45 seconds)
Executing (Extract by Mask): ExtractByMask "World Elevation Service" "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\locBuffer" "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\bufferExtract"
Start Time: Mon Feb 23 09:14:45 2015
ERROR 999999: Error executing function.
The table was not found. [VAT_bufferExtract]
(Esri GeoDatabase) General function failure
ERROR 010213: Error in reading raster World Elevation Service.
ERROR 010325: Run-time error - ***.
ERROR 010067: Error in executing grid expression.
Failed to execute (Extract by Mask).
Failed at Mon Feb 23 09:14:49 2015 (Elapsed Time: 4.03 seconds)
Failed to execute (HighestPointsNearLocations2).
Failed at Mon Feb 23 09:14:50 2015 (Elapsed Time: 6.05 seconds)
```

However it is successful when run the tool using a local elevation dataset it works just fine...
```
Executing: HighestPointsNearLocations2 imp "5 Kilometers" elevation C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0003
Start Time: Mon Feb 23 09:17:52 2015
Executing (Buffer): Buffer imp "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\locBuffer" "5 Kilometers" FULL ROUND NONE # PLANAR
Start Time: Mon Feb 23 09:17:53 2015
Succeeded at Mon Feb 23 09:17:53 2015 (Elapsed Time: 0.35 seconds)
Executing (Minimum Bounding Geometry): MinimumBoundingGeometry "C:\Workspace\ArcGIS 
...
...
...
Succeeded at Mon Feb 23 09:18:08 2015 (Elapsed Time: 0.22 seconds)
Executing (Delete Field): DeleteField C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0003 XCoord;YCoord;Z
Start Time: Mon Feb 23 09:18:08 2015
Dropping XCoord from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0003...
Dropping YCoord from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0003...
Dropping Z from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0003...
Succeeded at Mon Feb 23 09:18:09 2015 (Elapsed Time: 0.65 seconds)
Succeeded at Mon Feb 23 09:18:10 2015 (Elapsed Time: 17.46 seconds)
```
![image](https://cloud.githubusercontent.com/assets/3093182/6332792/0e19b33c-bb3d-11e4-9421-00d7cd0541c3.png)


I'm not confident that the problem is solely due to problems in the tool, but possibly in the elevation service. At this time I don't have anything else to try it with. :(

**Comment by conklinbd** [comment] 2015-02-23 17:23
Can you try with the AGOL elevation service and see if the problem exists?

**Comment by mfunk** [comment] 2015-02-23 17:46
Unfortunately the ArcGIS.com's 'terrain' service (http://www.arcgis.com/home/item.html?id=58a541efc59545e6b7137f961d7de883) cannot be added to ArcMap. I can use **Add From ArcGIS Online**, search for 'terrain' but when you click **Add** nothing happens.

If I go and add a direct server connection...the connection is emtpy for me (permissions?):

![image](https://cloud.githubusercontent.com/assets/3093182/6333240/4c7deeec-bb40-11e4-9b4d-62a4a225120b.png)

**Comment by conklinbd** [comment] 2015-02-23 18:00
Are you signed in with your http://afmie.maps.arcgis.com/home/ account?

**Comment by mfunk** [comment] 2015-02-23 18:10
Esri Global Account. I'll give it a try though.

**Comment by conklinbd** [comment] 2015-02-23 18:16
Esri Global won't work. You need to use a Named User that is part of the organizational account.

**Comment by mfunk** [comment] 2015-02-23 18:18
I was able to add it that way. Guess my Global Account is worthless. Anyway with the AGOL Terrain dataset the tool works fine.

```
Executing: HighestPointsNearLocations2 imp "5 Kilometers" Terrain C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0004
Start Time: Mon Feb 23 10:13:49 2015
Executing (Buffer): Buffer imp "C:\Workspace\ArcGIS Defense Templates\Military_Aspects_of_Terrain_for_ArcGIS_10_1\Maps\Toolbox\scratch\scratch.gdb\locBuffer" "5 Kilometers" FULL ROUND NONE # PLANAR
Start Time: Mon Feb 23 10:13:50 2015
Succeeded at Mon Feb 23 10:13:50 2015 (Elapsed Time: 0.28 seconds)
Executing (Minimum Bounding Geometry): MinimumBoundingGeometry "C:\Workspace\ArcGIS 
...
...
...
Start Time: Mon Feb 23 10:16:01 2015
Succeeded at Mon Feb 23 10:16:02 2015 (Elapsed Time: 0.22 seconds)
Executing (Delete Field): DeleteField C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0004 XCoord;YCoord;Z
Start Time: Mon Feb 23 10:16:02 2015
Dropping XCoord from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0004...
Dropping YCoord from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0004...
Dropping Z from C:\Workspace\Test\TestForErikReid\aTarget.gdb\mfHPNL0004...
Succeeded at Mon Feb 23 10:16:02 2015 (Elapsed Time: 0.18 seconds)
Succeeded at Mon Feb 23 10:16:03 2015 (Elapsed Time: 2 minutes 13 seconds)
```

![image](https://cloud.githubusercontent.com/assets/3093182/6333840/3601d638-bb45-11e4-90e1-11a72ed6cc5f.png)

As I suspect the problem could very well be with OUR elevation services and not the tool. Going to close this one out.

**Closed** 2015-02-23 18:18 UTC
Labels: bug, Military Team, priority-high, scrum-in current sprint, status-in progress
