### ISSUE TITLE
Incident Point isn't a required parameter, however, if the tool doesn't get the parameter it will fail

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/solutions-geoprocessing-toolbox#14] opened 2014-01-31 16:23 UTC
Please update the ERG By Placard and ERG by Chemical tool to have the incident point parameter as required not optional. 

Incident Point isn't a required parameter, however, so if the user runs the tool without it will proceed through validation then fail once executed.

**Comment by joebayles** [comment] 2015-01-12 21:00
@jeffbaranyi, were you tracking this issue? Was there a fix ever implemented on your side?

**Comment by joebayles** [comment] 2015-02-09 21:47
Assigned @jeffbaranyi just in case his team solved the issue, otherwise I'll reclaim it.

**Comment by conklinbd** [comment] 2015-02-12 13:14
reassigning back to Joe Bayles since this tool is owned by our team and we need to fix it.

**Comment by joebayles** [comment] 2015-02-12 18:30
After talking to @mfunk, he's going to look at this and get back to us.

**Comment by mfunk** [comment] 2015-02-12 22:53
OK so as I understand (and remember) on this one is that the Incident Point feature set (which is set as Required/Input) is validated as ready to run, even though there is no actual point geometry as any input. When you open the tool dialog the tool looks like it is ready to run...

![image](https://cloud.githubusercontent.com/assets/3093182/6178561/fae3b306-b2c4-11e4-9354-1dfc5c91b183.png)

However, this is an issue with all feature sets. Not just this tool, for example the Observers and Targets input feature sets in Linear Line Of Sight are marked as ready-to-go when you open the tool...
![image](https://cloud.githubusercontent.com/assets/3093182/6178631/abbc05b6-b2c5-11e4-9c03-a59e310291c5.png)

If you just click the Run on the ERG tools the tool fails with a custom error:
```NO SPILL POINT! This tool requires a spill point to be supplied```

The more generic error would be ```empty geometry`` somewhere in the tool. So the problem here basically boils down to the validation done against a feature set should check that an actual geometry exists before the tool can be run. For scripted tools, it might be possible to hack together something in the tools Validation in UpdateMessages that does a GetCount against the Input Incidents parameter. However this is NOT an option for Model Builder tools, which makes me believe that this should really go to the GP team as an enhancement for feature sets in Desktop. Unfortunately I don't think it will be a major priority on GP's TODO list. Just being honest here.

**Comment by mfunk** [comment] 2015-02-12 23:01
BTW, this may come back from GP as a "as designed" comment. If there is a definite need to resolve (not "fix") this for ERG tools it will ONLY be for the ERG tools. I do not think this is a good UX for tools. Mostly because until you add a single input point to Incident Points, there will be a red error X over Incident Points... meaning it is an error (though not really as we are forcing it to be that way).

**Comment by joebayles** [comment] 2015-02-12 23:25
@LindsayThomas , after talking to @mfunk and reading what he mentioned above, I think we missed the boat for changing how in memory feature sets are handled in desktop. He's going to talk to the GP team about this specific instance and see what they suggest. As far as your specific issue is concerned, I don't know that we can update the tool, but we can update the documentation to specify the parameter requirements, i.e. "NOTE: You must select an Incident Point. If the Input Feature Set is empty, the tool will fail."

Let us know what you think.

**Comment by LindsayThomas** [comment] 2015-02-13 14:20
@joebayles  @mfunk  Sounds good.  I think it is fine to leave in the documentation. I didn't realize this was a Core issue when I reported it.

**Comment by mfunk** [comment] 2015-02-20 22:45
Hey @LindsayThomas can you check out @joebayles doc changes? If they are acceptable lets close this issue out. If not we will fix again. Thanks!

**Comment by csmoore** [comment] 2015-03-03 16:38
@mfunk this can probably be auto-closed as "unverified" at this point

**Closed** 2015-03-03 16:42 UTC
Labels: enhancement, known-issue, Military Team

**Comment by LindsayThomas** [comment] 2015-03-04 15:50
I reviewed the change, they look good.
