### ISSUE TITLE
Two Clearing Operations PY scripts contain "ESRI_variable" swapped variables

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-geoprocessing-toolbox#603] opened 2017-09-19 14:57 UTC
The GRGUtilities.py and NumberFeatures.py scripts contain "ESRI_variable" swapped variables from some prior packaging.  Not a very serious issue, but seems messy. Also worry a bit what happens if a project containing the toolbox referencing this code gets packaged again, or with other tools.
Some of them are commented out (in GRGUtilities.py), others are not (in NumberFeatures.py).
![image](https://user-images.githubusercontent.com/3801392/30598976-331164c0-9d29-11e7-92c2-c3806bb3dc7f.png)
![image](https://user-images.githubusercontent.com/3801392/30598994-40be9ce6-9d29-11e7-8565-b0f3c285c7cf.png)

**Comment by mfunk** [comment] 2017-09-19 15:34
@BobBooth These are all left over from the original coding of "Number Features", "Point Target GRG" and "Canvas Area GRG". The previous sprint was about equivalency, and not refactoring, cleanup, etc. While most of the variables were commented out (not needed) they should not affect the operation of the tool... and therefore not a bug.

**Comment by adgiles** [comment] 2017-12-05 10:51
Addressed in PR #638

**Closed** 2017-12-21 17:17 UTC
Labels: A-feature, E-verified, G - Defense Team, N - Clearing Operations, V - ArcGIS Pro
