### ISSUE TITLE
Range Rings (in ArcGIS Pro 1.2) Model - not applying symbology or labels from Layer file.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-geoprocessing-toolbox#415] opened 2016-04-06 18:13 UTC
Range Rings (in ArcGIS Pro 1.2) Model - not applying symbology or labels from Layer file.  Yser can manually apply the Layer file. 

If applied manually:
Labels for range rings appear.
Labels for radials do not appear,  unless user manually turns on labels after applying Layer file..

**Comment by mfunk** [comment] 2016-09-28 19:42
Duplicate of #379

**Closed by mfunk** 2016-09-28 19:42 UTC
Labels: B - Bug, B - Duplicate, F - Visibility, G - Defense Team, N - Visibility and Range, priority-moderate, V - ArcGIS Pro
